[versions]
paper-api = "1.21.10-R0.1-SNAPSHOT"
adventure = "4.25.0"

[libraries]
jb-annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.2" }
jspecify = { group = "org.jspecify", name = "jspecify", version = "1.0.0" }
logger = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }
brigadier = { group = "com.mojang", name = "brigadier", version = "1.0.18" }

adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-serializer-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }


velocity-api = { group = "com.velocitypowered", name = "velocity-api", version = "3.4.0-SNAPSHOT" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.0.1" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "2.0.0-beta.19" }
dotenv = { id = "co.uzzu.dotenv.gradle", version = "4.0.0" }
